apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ml7q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ml7q
    app.kubernetes.io/part-of: integ-app-ywvn
  name: hacbs-test-project-ml7q
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ml7q
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ml7q
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-pfab-tenant/integ-app-ywvn/hacbs-test-project-ml7q@sha256:548b08427f0816c54d60533eb03998e45476703ed81446e4a26d4b2f60521b20
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
